### ISSUE TITLE
Navigation & locale switcher

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wp20.wordpress.net#1]
Update the main navigation and locale switcher to match the designs:

Note: the header is not in scope for this ticket and will be done in #6 

Desktop

![Local Nav Bar](https://user-images.githubusercontent.com/1017872/225155174-7cce73bc-3495-4569-b321-e8518e6a15be.png)

Mobile

![Screen Shot 2023-03-15 at 11 18 14 AM](https://user-images.githubusercontent.com/1017872/225155199-56559bb5-59a6-4489-93af-6e80846d124c.jpg)

### Locale switcher

`mu-plugins` code has been added but the initialisation and rendering has been commented as it's currently broken.

See

https://github.com/WordPress/wp20.wordpress.net/blob/c87aadffe9b949293ff725728c9def2e26c6fe0e/wp-content/themes/twentyseventeen-wp20/header.php#L32-L37

https://github.com/WordPress/wp20.wordpress.net/blob/c87aadffe9b949293ff725728c9def2e26c6fe0e/wp-content/mu-plugins/locales.php#L17-L18

If it runs these errors are displayed:

```
WordPress database error: [Table 'wordpress.wporg_locales' doesn't exist]
SELECT locale FROM wporg_locales

Fatal error: Uncaught Error: Undefined constant "WordPressdotorg\LocaleDetection\SITECOOKIEPATH" in /var/www/html/wp-content/mu-plugins/locale-detection/class-detector.php:81 Stack trace: #0 /var/www/html/wp-content/mu-plugins/locale-detection/class-detector.php(56): WordPressdotorg\LocaleDetection\Detector->set_locale() #1 /var/www/html/wp-content/mu-plugins/locale-detection/locale-detection.php(24): WordPressdotorg\LocaleDetection\Detector->__construct() #2 /var/www/html/wp-content/mu-plugins/locale-detection/locale-detection.php(31): WordPressdotorg\LocaleDetection\init() #3 /var/www/html/wp-content/mu-plugins/locales.php(17): require_once('/var/www/html/w...') #4 /var/www/html/wp-settings.php(372): include_once('/var/www/html/w...') #5 /var/www/html/wp-config.php(254): require_once('/var/www/html/w...') #6 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...') #7 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...') #8 /var/www/html/wp-admin/plugins.php(10): require_once('/var/www/html/w...') #9 {main} thrown in /var/www/html/wp-content/mu-plugins/locale-detection/class-detector.php on line 81 Notice: Function is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /var/www/html/wp-includes/functions.php on line 5835 Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /var/www/html/wp-includes/functions.php on line 5835
There has been a critical error on this website.
```

**Comment by iandunn** [comment]
That's a custom database table on the w.org network. We can probably just export/import it to this site.

**Comment by StevenDufresne** [comment]
The layout is addressed in #7. However, location detection fixes are not included in that PR.

**Comment by pablohoneyhoney** [comment]
Related to [wayfinding](https://github.com/WordPress/wp20.wordpress.net/issues/4#issuecomment-1470481955) (making sure people understand where they are), in mobile we need to explicitly say the title of the page/view, perhaps instead of "menu"?

And in the list within dropdown, it needs to be much clearer what option is highlighted (if the word menu subs the title when open, per note above).

<img width="538" alt="Screen Shot 2023-03-15 at 7 31 32 PM" src="https://user-images.githubusercontent.com/25516611/225408257-187d857e-883a-435d-9a68-d46bbb6b17b0.png">

**Comment by adamwoodnz** [comment]
Final designs @renintw @StevenDufresne 

![Screen Shot 2023-03-28 at 9 52 27 AM](https://user-images.githubusercontent.com/1017872/228063951-1779103c-8c02-452e-a9e1-9a8354417d89.jpg)

![Screen Shot 2023-03-28 at 9 53 07 AM](https://user-images.githubusercontent.com/1017872/228064103-bba8c052-c7b3-4e83-b093-4630f3d66567.jpg)

**Comment by StevenDufresne** [comment]
> Final designs @renintw @StevenDufresne
> 
> ![Screen Shot 2023-03-28 at 9 52 27 AM](https://user-images.githubusercontent.com/1017872/228063951-1779103c-8c02-452e-a9e1-9a8354417d89.jpg)

"What's on" is the homepage isn't it? Will the menu ever have the caption "menu" in that case or only when it's toggled open?

**Comment by StevenDufresne** [comment]
I also think we'll need to add some text overflow handling in the language dropdown. Some of the languages are lengthy.

**Comment by adamwoodnz** [comment]
> "What's on" is the homepage isn't it? Will the menu ever have the caption "menu" in that case or only when it's toggled open?

Correct, and not sure, @marko-srb?

**Comment by StevenDufresne** [comment]
> > "What's on" is the homepage isn't it? Will the menu ever have the caption "menu" in that case or only when it's toggled open?
> 
> Correct, and not sure, @marko-srb?

Here are 2 options: 
- Shows the page name
- Changes the label to "Menu"

| Option 1 | Option 2 | Closed | 
| --- | --- |  --- |
| ![localhost_8888_news__locale=sl_SI (1)](https://user-images.githubusercontent.com/1657336/228152146-68435545-3dd7-4dc5-a12f-966ae2ecc622.png) | ![localhost_8888_live_](https://user-images.githubusercontent.com/1657336/228152369-d2787bed-f73b-4393-9cbc-04ffe2eb0b64.png) | ![localhost_8888_news__locale=sl_SI](https://user-images.githubusercontent.com/1657336/228152155-163dada5-40ab-475c-b861-35101bfbf8a7.png) |

**Comment by adamwoodnz** [comment]
> Here are 2 options

I like option 2, where it says the current page title when closed, and Menu when open. I think that way the text is useful in both states.

**Comment by adamwoodnz** [comment]
I've noticed that there's been a regression in the sticky header. Some change in markup may have broken the JS, possibly adding the `wrap` class, although removing that doesn't fix it for me.

**Comment by StevenDufresne** [comment]
> I've noticed that there's been a regression in the sticky header. Some change in markup may have broken the JS, possibly adding the `wrap` class, although removing that doesn't fix it for me.

Yeah I noticed that too. I already added a fix for that in this PR.

**Comment by marko-srb** [comment]
Sorry, I was AFK for a few days. 


> I like option 2, where it says the current page title when closed, and Menu when open. I think that way the text is useful in both states.

Design intended it to work like this. I believe all states were in the design already in Figma. 

When open — says Menu. When closed (user is on dedicated page) it says that page name. 
"What's on?" is the homepage. 

Thanks!
