### ISSUE TITLE
Replace select2 with selectWoo

### ISSUE THREAD

**Issue by iandunn** [WordPress/wp20.wordpress.net#16]
https://github.com/woocommerce/selectWoo is better for a11y

**Comment by adamwoodnz** [comment]
I don't seem to be able to enter the locale search field with my keyboard after activating the switcher dropdown. Is this a known issue @iandunn ?

**Comment by iandunn** [comment]
🤔 I'm not able to do that in the commit before #24 either (ac8e726). I opened #70 for it 👍🏻
