### ISSUE TITLE
Theme updates: general layout, colors, typography, templates

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wp20.wordpress.net#2]
Implement main theme updates from wp15:

1. Update content and images (including shared template parts like header and footer)
2. Update typography and colours
3. Remove unnecessary styles

The News, News single and Swag page layouts should be complete after this is merged. The main navigation will require more work in #1, and the swag assets will be added in #5.

### Desktop

| Home header | News | Single | Swag |
|-|-|-|-|
| ![Community](https://user-images.githubusercontent.com/1017872/225161045-713741ce-ce06-4f8f-9f69-8755ebf3c31a.png) | ![News](https://user-images.githubusercontent.com/1017872/225158451-2ea2a963-3fac-4c8f-b6d0-7a12c8b368d7.png) | ![News Single](https://user-images.githubusercontent.com/1017872/225158716-5d726740-5311-4547-a542-6143779a094e.png) | ![Swag](https://user-images.githubusercontent.com/1017872/225158757-0a179385-7325-4a04-a4a7-9c2947bf1800.png) |

### Mobile

| Home header | News | Single | Swag |
|-|-|-|-|
| ![Navigation states](https://user-images.githubusercontent.com/1017872/225161089-b842f626-0322-4e0b-a55c-276d75cc993e.png) | ![News — Mobile](https://user-images.githubusercontent.com/1017872/225158504-8e10df53-23db-4bde-ad59-12b947a8774e.png) | ![News Single — Mobile](https://user-images.githubusercontent.com/1017872/225158947-52993d5a-4a39-4aa3-a14b-81001b9c5ef9.png) | ![Swag — Mobile](https://user-images.githubusercontent.com/1017872/225158926-9cc7accb-807d-475c-8357-faae65917f16.png) |

**Comment by pablohoneyhoney** [comment]
Relevant notes for this one in the other issues #1 #3 #4

**Comment by marko-srb** [comment]
👋

**Grand Finale Update.**
—
**A. Overview**
Joen, Pablo, and I made lots of updates to the wp20.wordpress.net design. To keep things simple, I recorded a video that explains many of these. On the other hand, the most important things to pay attention to are:

- typography and spacings are changed on each page (everywhere)
- hero sections
- footers
- social wall edits (card's infos are tweaked a bit)

**B. Video walkthrough**
https://user-images.githubusercontent.com/111751264/227341641-47020b9e-50f8-4c22-a3e7-866eea121d8f.mp4

**C. Next steps**
C.1. We are awaiting a signoff from DC
C.2. We can support you in implementing this by 'style guide' and anything else that you may need

cc:
@jasmussen
@pablohoneyhoney 
@adamwoodnz 
@StevenDufresne

**Comment by StevenDufresne** [comment]
For me, that video was very helpful. Thanks for putting it together!

> We are awaiting a signoff from DC

Has that conversation been initiated anywhere else or are the pings in your comment the only request for feedback/signoff?

**Comment by marko-srb** [comment]
> For me, that video was very helpful. Thanks for putting it together!
> 
> > We are awaiting a signoff from DC
> 
> Has that conversation been initiated anywhere else or are the pings in your comment the only request for feedback/signoff?

Yup, we shared on all communication channels. Ping in P2, ping here, ping on Slack channel, and DM. :) Thanks!

**Comment by marko-srb** [comment]
👋
@adamwoodnz 
@StevenDufresne 

We have received feedback from both Pablo and Kelly and I believe we can start implementing the site. 

https://user-images.githubusercontent.com/111751264/227690415-5adf526f-e88b-4151-9899-b1b1103de8f4.mp4
(play speed: 2x or 2.5x :) )

Above is a quick video, that explains what was required to update, all is done, and therefore we should be able to start the implementing. 

Let me know in case you need anything else from our end. Thank you!

cc: @jasmussen @pablohoneyhoney

**Comment by adamwoodnz** [comment]
This is now broken into sub tasks, see https://github.com/WordPress/wp20.wordpress.net/milestone/1
