### ISSUE TITLE
Integrate wporg locale switcher with Language Translator

### ISSUE THREAD

**Issue by iandunn** [WordPress/wp20.wordpress.net#22]
#17 and #18 setup the same localization flow that we used on wp15, so that we can have high-quality translation on the site pages, menu items, etc.

We still need the Language Translator plugin for the posts, though. What would be a good way to integrate the two from a visual and UX perspective?

One idea would be to only show the locale switcher on posts, and show the Translator plugin everywhere else. We might also be able to get the Translator plugin to use the UI from the locale switcher, since that's what is in the design.

@marko-srb, @jasmussen

**Comment by jasmussen** [comment]
I've never used the language translator plugin, would you be available to share a screenshot?

Who will see the translator plugin, and how will it appear? Is it a small icon or something? 

Ultimately, if this plugin is only available to editors or admins that are signed in, we don't have to worry too much about the visuals, IMO. But happy to take a visual pass if you can share a screenshot 👍 👍

**Comment by marko-srb** [comment]
Hmm, we need to make a different UI button for this, as it is a different category (abstractly speaking) than translate the pages of the website. Let me see if we can find good solutions and I'll be back with suggestion.

**Comment by iandunn** [comment]
It's for visitors rather than translators. You can see it on the current site in the bottom left:

<img width="721" alt="Screenshot 2023-03-20 at 11 16 13 AM" src="https://user-images.githubusercontent.com/484068/226430618-e11432fd-e8d9-47e6-8f8d-e535bcd670b2.png">

<img width="726" alt="Screenshot 2023-03-20 at 11 19 45 AM" src="https://user-images.githubusercontent.com/484068/226431359-62fc3b80-4b5f-4dee-9bd2-9d03ac0789a2.png">


There's now some discussion about volunteers manually translating _post_ content as well, but I'm not sure what tools would be used, and if we'd still use Language Translator for the locales that aren't manually translated. So, it might be good to pause on this until we know more.

**Comment by jasmussen** [comment]
Probably important to consider the prominence of this button here. Even if it is visible to everyone, it's definitely not a primary action, so visually it should be weighted as such. In that same corner might still work, just vastly reduced, perhaps like so?

<img width="998" alt="Screenshot 2023-03-21 at 08 54 42" src="https://user-images.githubusercontent.com/1204802/226546459-3a9bfa56-baa6-401f-bf99-bece9b21afdc.png">

I'll refer to Marko if he has any thoughts on it.

**Comment by marko-srb** [comment]
This should be omitted, as per discussion on P2 that we have Google translate that will do this...

**Comment by iandunn** [comment]
Yup! I think we can close this 👍🏻 

To clarify the details, my understanding is that the wporg locale switcher will translate the static content like page templates, and users can use their browser to translate dynamic content like posts. That's how the site is currently working, since I disabled the Google plugin. Does that sound right to you?
