### ISSUE TITLE
Fix 404 layout

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wp20.wordpress.net#43]
Probably related to floats, search box also needs work

| Desktop | Tablet | Mobile |
|-|-|-|
| ![wp20 mystagingwebsite com_blah(Desktop)](https://user-images.githubusercontent.com/1017872/229939839-c67ec650-89a1-43e6-94ed-771b8a3185d2.png) | ![wp20 mystagingwebsite com_blah(iPad)](https://user-images.githubusercontent.com/1017872/229939848-48287c8c-58bc-4e06-9d5e-16c806f2a846.png) | ![wp20 mystagingwebsite com_blah(iPhone X)](https://user-images.githubusercontent.com/1017872/229939865-5f6b5f51-8589-4659-8ba6-8d08e933c25b.png) |

**Comment by StevenDufresne** [comment]
Is this consider critical for launch? Should we add it to the launch milestone?
