### ISSUE TITLE
Navigation title on author archive on mobile.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wp20.wordpress.net#45]
When viewing the author archive, the page title is the first post on mobile

It should probably be simpler, maybe just `Archives`

URL: https://wp20.mystagingwebsite.com/author/dansoschin/

| Before | After |
| --- | --- |
| ![wp20 mystagingwebsite com_author_dansoschin_(Pixel 5) (1)](https://user-images.githubusercontent.com/1657336/229955862-40eba0a9-29bc-428d-8624-822f1d2cc530.png) | ![wp20 mystagingwebsite com_author_dansoschin_(Pixel 5)](https://user-images.githubusercontent.com/1657336/229955867-03f9f95b-b3e0-404b-9dea-4c68b34e494c.png) |

**Comment by adamwoodnz** [comment]
In #44 I'm changing it to 'News', see [this comment](https://github.com/WordPress/wp20.wordpress.net/issues/46#issuecomment-1498071367)
