### ISSUE TITLE
Mobile menu title for single post is too long.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wp20.wordpress.net#46]
On mobile the titles are too big.

URL : https://wp20.mystagingwebsite.com/author/dansoschin/

## Options 

| Before | "Post" | Truncated |
| --- | --- | --- | 
| ![wp20 mystagingwebsite com_celebrate-with-wordpress_(Pixel 5)](https://user-images.githubusercontent.com/1657336/229956422-eea7b64c-30e9-4d7a-863b-491ebbd611e6.png) |  ![wp20 mystagingwebsite com_celebrate-with-wordpress_(Pixel 5) (1)](https://user-images.githubusercontent.com/1657336/229956419-6bc2618d-3a42-498b-a197-d3b6902560c5.png) | ![wp20 mystagingwebsite com_celebrate-with-wordpress_(Pixel 5) (2)](https://user-images.githubusercontent.com/1657336/229956412-3ab73ee0-2409-4b26-8855-68b20c870eb5.png) |

**Comment by adamwoodnz** [comment]
Note that @marko-srb said to use 'News' for a single post in his feedback video (around 3:30), and it seems like that could extend to archive (author) as well:

https://user-images.githubusercontent.com/111751264/229902567-a6ef1278-a2b8-4ce5-b7e6-7160c3cd2a2e.mp4


That's the solution I've gone with in #44
