### ISSUE TITLE
Redundant messaging when filtering events.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wp20.wordpress.net#47]
I'm not sure this will be covered in #3 , but when you filter events, the response text in the content is the same as the footer.

"Don't see your city ..."

<img src="https://user-images.githubusercontent.com/1657336/229957997-45ae95f1-4ff2-4451-a477-99ae8a9271a4.jpg" width="300px" />

**Comment by iandunn** [comment]
It looks like that was [removed](https://github.com/WordPress/wp20.wordpress.net/pull/37/files#r1151302300) in #37. I can't reproduce the screenshot above. Are you still seeing it?

**Comment by StevenDufresne** [comment]
I cannot. It's likely that the test environment was not up to date when I tested. Closing.
