### ISSUE TITLE
Add downloadable assets to Swag page

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wp20.wordpress.net#5]
Markup should be done in #2 

Add all the assets and link them.

**Comment by StevenDufresne** [comment]
Assets requested in figma: https://www.figma.com/file/3veAfpzTQ82v8G3sbvaJZh?node-id=369:2626#388203074

**Comment by marko-srb** [comment]
Download-able assets for 'Swag' page are here: 

https://drive.google.com/drive/folders/1edS0Ty5-axWKClJEEOhBQrrlkxxdoII4?usp=share_link

**Comment by adamwoodnz** [comment]
Done in https://github.com/WordPress/wp20.wordpress.net/commit/a6ed4174abf8baa18f2876b09a7647e083dd99e1
