### ISSUE TITLE
Horizontal scrolling on mobile in Firefox

### ISSUE THREAD

**Issue by iandunn** [WordPress/wp20.wordpress.net#51]
It's possible to scroll horizontally. I can only reproduce it in Firefox at the mobile breakpoint.

![Screenshot 2023-04-06 at 3 41 44 PM](https://user-images.githubusercontent.com/484068/230506954-8b8b52e1-9b82-4829-bfe9-3d402b4881e4.png)

**Comment by adamwoodnz** [comment]
Fixed in https://github.com/WordPress/wp20.wordpress.net/commit/61bbe8bb6393889323820251d67099a44a20bbe0
