### ISSUE TITLE
Long search label text expands search box

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wp20.wordpress.net#56]
If you change the language of the main page (https://wp20.mystagingwebsite.com) to [Deutsch](https://wp20.mystagingwebsite.com/?locale=de_DE), the translated text expands the 'search events' label which breaks to two lines and expands the input field border.

I'd expect input field shouldn't grow to the full height. If it's intentional, perhaps moving the magnifying glass to be vertically aligned to the middle of the field would look better.

Browser: Chrome 111
OS: macOS Ventura

Deutsch:
<img width="1443" alt="Screenshot 2023-04-10 at 5 06 00 PM" src="https://user-images.githubusercontent.com/7133400/230999732-e903e7ff-b785-4278-8f77-a00546d5ca5f.png">

English:
<img width="1464" alt="Screenshot 2023-04-10 at 5 05 46 PM" src="https://user-images.githubusercontent.com/7133400/230999714-aa9010fe-a648-47d8-b123-da370eb102e1.png">

**Comment by iandunn** [comment]
Ah, good catch! That wasn't intentional, but it should be fixable 👍🏻
