### ISSUE TITLE
Add social sharing options to posts

### ISSUE THREAD

**Issue by DanSoschin** [WordPress/wp20.wordpress.net#87]
In the prior iteration of the WP20 site, each post had social sharing buttons. I am hopeful we can add these back to posts to help with amplification.

**Comment by adamwoodnz** [comment]
I've turned these back on at https://wordpress.com/marketing/sharing-buttons/wp20.wordpress.net?site=wp20.wordpress.net, however I wonder whether it's too much on the News page where all the posts are listed, and should only be displayed on the single news page?

| News | Single |
|-|-|
| ![Screen Shot 2023-04-20 at 8 39 06 AM](https://user-images.githubusercontent.com/1017872/233194791-5d39dac9-2669-49ab-8dd0-f56838d5eb07.jpg) | ![Screen Shot 2023-04-20 at 8 39 24 AM](https://user-images.githubusercontent.com/1017872/233194813-13ec07f3-a734-406b-8eab-6c90a264d206.jpg) |

For now I have hidden them on the list page, @marko-srb @jasmussen what do you think?

**Comment by jasmussen** [comment]
Let's not show these on the list page 👍 

This looks like it's using Jetpack. I haven't looked into the details on jetpack features as far as what's possible. But I would minimize the footprint quite a bit, something like this:

<img width="1036" alt="Screenshot 2023-04-20 at 09 50 05" src="https://user-images.githubusercontent.com/1204802/233297537-ef4f4730-fef9-406a-a7e9-e11de876733a.png">

This would be possible with the social links block. Mainly, the border, the "Share this", and the labels all produce some visual noise that's entirely secondary to the content of the post, so I'd avoid it if we could.

**Comment by adamwoodnz** [comment]
Fixed by https://github.com/WordPress/wp20.wordpress.net/commit/41ac47b0715cbf19bc1d6e4f3b83df76081c227e, https://github.com/WordPress/wp20.wordpress.net/commit/7d80d2f4267a65d057feb14e5b12328c8155b48b, https://github.com/WordPress/wp20.wordpress.net/commit/918c42d85307f94573834080adcd317bfa52fd75, https://github.com/WordPress/wp20.wordpress.net/commit/6e3957b1052850feae4640e84f8fdd64370a61ca
